-- ============================================================
-- OpenSe Seed Index
-- ============================================================
-- Seed data is now split by domain under `supabase/seeds/`.
-- Execution order is configured in `supabase/config.toml` under:
--   [db.seed].sql_paths
--
-- Files currently executed:
--   00_cleanup.sql
--   10_auth_users.sql
--   20_public_core.sql
--   30_etl_core.sql
--   40_stoqr_reference_membership.sql
--   50_stoqr_catalog_inventory.sql
--   55_stoqr_reports_demo.sql
--   60_admin_audit.sql
--   90_synthetic_volume.sql
--
-- Note: StoQR product categories are no longer a dedicated table.
-- Optional categorization should be stored in products.custom_fields JSONB.