-- ============================================================
-- OpenSe Seed Index
-- ============================================================
-- Seed data is now split by domain under `supabase/seeds/`.
-- Execution order is configured in `supabase/config.toml` under:
--   [db.seed].sql_paths
-- Automatic CLI seeding is disabled with [db.seed].enabled = false.
-- Use `./setup.sh` option 2 to insert these seed files manually.
-- Runtime app catalog rows and app permission codes are migration-owned;
-- these files load demo/reference/test data only.
--
-- Files currently executed:
--   00_cleanup.sql
--   10_auth_users.sql
--   20_public_core.sql
--   30_etl_core.sql
--   40_stoqr_reference_membership.sql
--   50_stoqr_catalog_inventory.sql
--   55_stoqr_reports_demo.sql

--   56_stoqr_procurement_workflows.sql
--   60_admin_audit.sql
--   90_synthetic_volume.sql
--
-- Note: StoQR folders are the storage hierarchy. Product stock membership and
-- per-folder limits live in stoqr.product_folder_stocks; products retain a
-- derived quantity_on_hand total for compatibility.
