#!/bin/sh
set -eu

while read local_ref local_sha remote_ref remote_sha
do
  if [ "$remote_ref" = "refs/heads/main" ]; then
    echo "Pushing to main: running local production Docker builds first..."
    cd opense-stack
    docker compose -f docker-compose.prod.yml build
  fi
done
